
#ifndef ENCFLAGDATA_H
#define ENCFLAGDATA_H

#define ENC_FLAG_DATA_TAG 'TDFE' // EFDT

// 加密文件识别用标识
//#define IDENTITY_FLAG "Safe By 张乐  \r\nQQ:575599766  \r\nEleZhangLe@163.com            \r\nTel:18778056037\r\n版权所有.    \r\n注意：此文件已加密，禁止直接修改文件的内容!   \r\nCAUTION:This file has been encrypted,DO NOT edit this file!You may DESTROY it!\0\0\0\0\0\0\0\0\0\0\0\0"
// 110419 for shd Mr.Dong
#define IDENTITY_FLAG "\x07\x97\x17\x88 SDSQ encrypted 提醒：请不要直接修改文件信息，否则可能造成文件损坏.\r\nCAUTION:This file has been encrypted,DO NOT edit this file directly!You may DESTROY it!\0\0"

// 记录识别用标识串字节数（即空间大小）,注意：需要大于IDENTITY_FLAG串的长度
// #define IDENTITY_FLAG_BYTES 230
// 110419 for shd Mr.Dong
#define IDENTITY_FLAG_BYTES 200 

// 文件加密标识占用字节数
#define ENCRYPT_HEAD_LENGTH		1024

//{{ For BeiJing Mr.Chen
// 私有数据字节数
#define PRIVATE_DATA_LEN 256
#define PRIVATE_LABELSTRING "CJKernal:Data"
// 私有数据在文件头中的偏移量，注意：必须大于IDENTITY_FLAG_BYTES的值
#define PRIVATE_DATA_OFFSET 256
//}}


// 密钥字符数
#define CRYPTO_KEY_CHARS	32

// FingerPrint计算结果字节数
#define FINGERPRINT_BYTES	16

// 策略
#define POLICY_FLAG			0xd4c2dfb2
// 指纹
#define FINGERPRINT_FLAG	'gniF'
// 基本扩展名
#define BASE_EXT_FLAG		'txEB'
// 过滤项
#define EXCEPT_EXT_FLAG		'tpxE'
// 加密目录
#define DIR_FLAG		'xFrS'

typedef struct _ENC_FLAG_DATA
{
	char	strFlag[IDENTITY_FLAG_BYTES];		// 加密标识串,可支持到IDENTITY_FLAG_BYTES*8位			起始位置:0		
	int		nVerNum;							// 版本号												起始位置:IDENTITY_FLAG_BYTES
}ENC_FLAG_DATA, *PENC_FLAG_DATA;

// 策略文件加密方式
enum EEncType
{
	eOrignal = 0x501805B2,
	eAES = 0x40B4FE4D
};

#endif
